services:
  nessie-catalog:
    image: projectnessie/nessie:0.76.6
    container_name: nessie-catalog
    ports:
      - "19120:19120"

  minio:
    image: minio/minio
    container_name: minio
    environment:
      MINIO_REGION_NAME: us-east-1
      MINIO_REGION: us-east-1
      MINIO_DOMAIN: minio
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin@2025
    ports:
      - "9000:9000"
      - "9001:9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    entrypoint: >
      /bin/sh -c "
      minio server /data --console-address ':9001' &
      sleep 5;
      mc alias set vbi_s3 http://localhost:9000 admin admin@2025;
      mc mb vbi_s3/local-lakehouse;
      tail -f /dev/null"

  trino-coordinator:
    image: trinodb/trino:476
    container_name: trino-coordinator
    ports:
      - "8080:8080"
    volumes:
      - ./trino_config/coordinator/config.properties:/etc/trino/config.properties
      - ./trino_config/catalog:/etc/trino/catalog
      - ./trino_config/jvm.config:/etc/trino/jvm.config

  trino-worker-1:
    image: trinodb/trino:476
    container_name: trino-worker-1
    volumes:
      - ./trino_config/worker/config.properties:/etc/trino/config.properties
      - ./trino_config/catalog:/etc/trino/catalog
    depends_on:
      - trino-coordinator

  trino-worker-2:
    image: trinodb/trino:476
    container_name: trino-worker-2
    volumes:
      - ./trino_config/worker/config.properties:/etc/trino/config.properties
      - ./trino_config/catalog:/etc/trino/catalog
    depends_on:
      - trino-coordinator