dbt_trino:              
  outputs:
    dev:
      type: trino
      method: none
      user: admin
      database: connector
      host: trino-coordinator
      port: 8080
      schema: staging
      threads: 1
  target: dev
