dbt_trino:              
  outputs:
    dev:
      type: trino
      method: none
      user: batman
      database: iceberg
      host: trino-coordinator
      port: 8080
      schema: staging
      threads: 1
  target: dev
